### ISSUE TITLE
Documentation Error - Change generator.rb to template.rb

### ISSUE THREAD

**Issue by Innarticles** [matteolc/rails-api-template#1]
Hi @matteolc,

You specified https://raw.githubusercontent.com/matteolc/rails-api-template/master/generator.rb
The correct link is:
https://raw.githubusercontent.com/matteolc/rails-api-template/master/template.rb

Please, correct. 

Thanks

**Comment by matteolc** [comment]
Hi @Innarticles 

Thanks for your feedback, I am happy someone is actively using this repo.

As you may have noticed this repo undergo a major version bump, README has now been updated accordingly.

Best
Matteo
